# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
    open-pull-requests-limit: 10
    groups:
      cargo:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "cargo"
    directory: "/rust"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "gradle"
    directory: "/fabric"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/forge"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/neoforge"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
