version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/rust"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      cargo:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "gradle"
    directory: "/fabric"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      gradle:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "gradle"
    directory: "/forge"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      gradle:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "gradle"
    directory: "/neoforge"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      gradle:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"